// SPDX-License-Identifier: AGPL-3.0-only
pub mod crawler;
pub mod hashing;
pub mod manifest;
pub mod migrate;
pub mod project_detect;
pub mod reader;
pub mod schemes;
pub mod suggest;
pub mod vcs;
pub mod version_sources;
